#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# miscellaneous
#alias sudo='doas'
alias \
	c='clear' \
	cat='bat' \
	groff='/usr/local/Cellar/groff/1.22.4_1/bin/groff'    # alias osx groff to homebrew groff

# Utilities
alias \
	u='app-cleaner.sh' \
	wtr='curl wttr.in' \
	wpass='wifi-password' \
	myip='curl ifconfig.co'

# Navigation
alias \
	..='cd ..' \
	...='cd ../..' \
	.3='cd ../../..' \
	.4='cd ../../../..' \
	.5='cd ../../../../..'

# brew
alias brewsyu='brew upgrade -v && cd $HOME/.config/brew && brew bundle -v && brew cu -afyv && cd && brew doctor -v'   # update all brew pkgs
alias brewfcrt='cd $HOME/.config/brew && brew bundle dump --describe && cd'    # create brewfile in $HOME/config/brew
alias brewfsyu='cd $HOME/.config/brew && brew bundle dump --force --describe && cd'    # update brewfile
alias cleanup='brew autoremove && brew cleanup && brew doctor -v'    # remove orphaned packages
alias brewdep='brew deps --tree --installed'    # list dependencies
alias brewls='brew list -1 --full-name'
alias outdated='brew outdated -v'

# Change "ls" to "exa"
alias \
	ls='exa -al --color=always --group-directories-first' \
	la='exa -a --color=always --group-directories-first' \
	ll='exa -l --color=always --group-directories-first' \
	lt='exa -aT --color=always --group-directories-first' \
	l.='exa -a | egrep "^\."'

# Colorize commands when possible.
alias \
	diff="diff --color=auto" \

# Colorize grep output (good for log files)
alias \
	grep='grep --color=auto' \
	egrep='egrep --color=auto' \
	fgrep='fgrep --color=auto'

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -iv" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="sudo shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	b="brew" \
	z="xpdf" \
	n="newsboat" \
	YT="youtube-viewer" \
	trem="transmission-remote"

# Adding flags
alias \
	df='df -h' \
	vifm='./.config/vifm/scripts/vifmrun' \
	ncmpcpp='ncmpcpp ncmpcpp_directory=$HOME/.config/ncmpcpp/' \
	mocp='mocp -M "$XDG_CONFIG_HOME"/moc -O MOCDir="$XDG_CONFIG_HOME"/moc' \
	lynx='lynx -cfg=~/.lynx/lynx.cfg -lss=~/.lynx/lynx.lss -vikeys'
#lf='/usr/local/bin/lfrun'

# Git
alias \
	gtg='cd $HOME/Downloads/gitthings' \
	addup='git add -u' \
	addall='git add .' \
	branch='git branch' \
	checkout='git checkout' \
	clone='git clone' \
	commit='git commit -m' \
	fetch='git fetch' \
	pull='git pull origin' \
	push='git push origin' \
	status='git status' \
	tag='git tag' \
	newtag='git tag -a'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# youtube-dl
alias \
	ydl="youtube-dl -x --audio-format mp3 -a $HOME/urls" \
	yta-aac="youtube-dl --extract-audio --audio-format aac " \
	yta-best="youtube-dl --extract-audio --audio-format best " \
	yta-flac="youtube-dl --extract-audio --audio-format flac " \
	yta-m4a="youtube-dl --extract-audio --audio-format m4a " \
	yta-mp3="youtube-dl --extract-audio --audio-format mp3 " \
	yta-opus="youtube-dl --extract-audio --audio-format opus " \
	yta-vorbis="youtube-dl --extract-audio --audio-format vorbis " \
	yta-wav="youtube-dl --extract-audio --audio-format wav " \
	ytv-best="youtube-dl -f bestvideo+bestaudio "

# Switch between shells
alias \
	tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'" \
	tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"

# Remind
alias \
	wrem='rem -cl+1 -@'\
	gcal='remind -cl -pp ~/.reminders/ | rem2ps -l -st 55 -shd 35 -se 25 -m 30x40cm | ps2pdf - > ~/.reminders/cal.pdf' \
	vcal='remind -cl -pp ~/.reminders/ | rem2ps -l -st 55 -shd 35 -se 25 -m 30x40cm | ps2pdf - > ~/.reminders/cal.pdf && xpdf ~/.reminders/cal.pdf' \
	urem='vim ~/.reminders/uni.rem' \
	prem='vim ~/.reminders/personal.rem'

# skim (pdf viewer)
alias \
	embed='skimpdf embed ' \
	unembed='skimpdf unembed '

# Terminal rickroll
alias rr='curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'

# Wget Command to Retrieve Whole Websites
alias wsd='wget --mirror --convert-links --page-requisites --no-parent -P $HOME/Documents/website-archives/'

# Generate and deploy personal website
alias gw='cd ~/.websites/hghann.github.io/ && rm -f ~/.websites/hghann.github.io/dst/.files && ~/.websites/hghann.github.io/bin/ssg6 src dst "Steve Blog" "https://hghann.github.io/" && rsync -av ~/.websites/hghann.github.io/dst/ ~/.websites/hghann.github.io/'
alias dw='cd ~/.websites/hghann.github.io/ && rm -f ~/.websites/hghann.github.io/dst/.files && ~/.websites/hghann.github.io/bin/ssg6 src dst "hghanns Blog" "https://hghann.github.io/" && rsync -av ~/.websites/hghann.github.io/dst/ ~/.websites/hghann.github.io/ && git add . && git commit -m "minor edits" && git push -u origin master'
