tap "astroidmail/astroid"
tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Core application library for C
brew "glib"
# Fuzzy matcher that uses std{in,out} and a native GUI
brew "choose-gui"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Configurable talking characters in ASCII art
brew "cowsay"
# Modern replacement for 'ls'
brew "exa"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Banner-like program prints strings as ASCII art
brew "figlet"
# Infamous electronic fortune-cookie generator
brew "fortune"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU troff text-formatting system
brew "groff"
# Improved top (interactive process viewer)
brew "htop"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Terminal file manager
brew "lf"
# Mac App Store command-line interface
brew "mas"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# RSS/Atom feed reader for text terminals
brew "newsboat"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Password manager
brew "pass"
# Pretty system information tool written in POSIX sh
brew "pfetch"
# Sophisticated calendar and alarm
brew "remind"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Cross-shell prompt for astronauts
brew "starship"
# Command-line interface to the freedesktop.org trashcan
brew "trash-cli"
# Internet file retriever
brew "wget"
# Show the current WiFi network password
brew "wifi-password"
# PDF viewer
brew "xpdf"
# Download YouTube videos from the command-line
brew "youtube-dl"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# View, print, and comment on PDF documents
cask "adobe-acrobat-reader"
# GPU-accelerated terminal emulator
cask "alacritty"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Multi-platform client-side cloud file encryption tool
cask "cryptomator"
# Web browser
cask "firefox"
# 3D parametric modeler
cask "freecad"
# Free and open-source image editor
cask "gimp"
# Utility to hide menu bar items
cask "hiddenbar"
# Vector graphics editor
cask "inkscape"
# Password manager app
cask "keepassxc"
# Tool to prevent the system from going into sleep mode
cask "keepingyouawake"
# Office suite
cask "libreoffice"
# Open-source firewall to block unknown outgoing connections
cask "lulu"
# Full TeX Live distribution with GUI applications
cask "mactex"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Media player based on MPlayer and mplayer2
cask "mpv"
cask "qtox"
# Keyboard-driven, vim-like browser based on PyQt5
cask "qutebrowser"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Instant messaging application focusing on security
cask "signal"
# PDF reader and note-taking application
cask "skim"
# Virtual machine client
cask "vmware-horizon-client"
# Binary releases of VS Code without MS branding/telemetry/licensing
cask "vscodium"
mas "Expenses", id: 1492055171
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
